// Valid or refused by BOTH layers: the application and `valid_stream_url` in 202610040001_url_stream_sources.sql.
// `pnpm check:migrations` runs them through it in a throwaway Postgres.
export const URL_CASES: [provider: "hls" | "dash" | "link", id: string, ok: boolean][] = [
  ["hls", "https://cdn.example.com/live/index.m3u8", true],
  ["hls", "https://cdn.example.com:8443/live/index.m3u8?token=abc&e=1", true],
  ["hls", "https://a.b.example.co.uk/x/master.m3u8", true],
  ["hls", "https://cdn.example.com/live/index.mpd", false],
  ["hls", "https://cdn.example.com/index.m3u8.txt", false],
  ["hls", "https://cdn.example.com/?u=a.m3u8", false],
  ["hls", "http://cdn.example.com/index.m3u8", false],
  ["hls", "https://127.0.0.1/index.m3u8", false],
  ["hls", "https://10.0.0.5:8443/index.m3u8", false],
  ["hls", "https://localhost/index.m3u8", false],
  ["hls", "https://printer.local/index.m3u8", false],
  ["hls", "https://app.internal/index.m3u8", false],
  ["hls", "https://nas.home.arpa/index.m3u8", false],
  ["hls", "https://user:pw@cdn.example.com/index.m3u8", false],
  ["hls", "https://user@cdn.example.com/index.m3u8", false],
  ["hls", "https://cdn.example.com/in dex.m3u8", false],
  ["hls", "https://cdn.example.com/a,b.m3u8", false],
  ["hls", "https://cdn.example.com/index.m3u8#frag", false],
  ["hls", "https://cdn.example.com/it's.m3u8", false],
  ["hls", "https://[::1]/index.m3u8", false],
  ["hls", "https://singlelabel/index.m3u8", false],
  ["hls", "https://cdn.example.com./live/index.m3u8", false],
  ["hls", "https://xn--a.com/live.m3u8", false],
  ["hls", "https://xn--bcher-kva.example/live.m3u8", false],
  ["hls", "https://bücher.example/live.m3u8", false],
  ["hls", "https://cdn.xn--p1ai/live.m3u8", false],
  ["hls", "https://my--cdn.example.com/live.m3u8", true],
  ["hls", "https://-cdn.example.com/a.m3u8", false],
  ["hls", "https://cdn-.example.com/a.m3u8", false],
  ["hls", "https://cdn.example.1/a.m3u8", false],
  ["hls", "https://cdn.example.0x1f/a.m3u8", false],
  ["hls", `https://${"x".repeat(64)}.example.com/a.m3u8`, false],
  ["hls", `https://${"x".repeat(63)}.example.com/a.m3u8`, true],
  ["hls", "https://home.arpa/a.m3u8", false],
  ["link", "https://www.example.com:1000/b", false],
  ["link", "https://www.example.com:1024/b", true],
  ["link", "https://www.example.com:65535/b", true],
  ["link", "https://www.example.com:65536/b", false],
  ["link", "https://www.example.com/a{b}", true],
  ["link", "https://www.example.com/a?b={c}", true],
  ["link", "https://www.example.com/a^b|c[1]", true],
  ["link", "https://www.example.com//a", true],
  ["dash", "https://cdn.example.com/live/manifest.mpd", true],
  ["dash", "https://cdn.example.com/live/manifest.m3u8", false],
  ["link", "https://www.example.com/watch/live", true],
  ["link", "http://www.example.com/", false],
  ["link", "https://192.168.1.10/", false],
  ["link", "javascript:alert(1)", false],
];
